# -*- coding: utf-8 -*-
"""safire_image_localization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1SBkY3HwSFg4oSF6lojb1_Vr5HAz9XQ_1

## Project Objective

This notebook runs SAFIRE, a pretrained image-forgery-localization model, on automobile images. It generates a pixel-level suspicion map to support human review of potentially manipulated regions. The map is evidence only and does not automatically prove that an image is forged.

## Clone the SAFIRE Repository
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/mjkwon2021/SAFIRE.git
# %cd SAFIRE

"""## Google Colab GPU Setup

SAFIRE requires a CUDA enabled GPU for inference
"""

!nvidia-smi

"""## Installing required dependencies"""

!pip install -q connected-components-3d SimpleITK monai scikit-image nibabel tqdm scipy opencv-python pycocotools albumentations
!pip install -q git+https://github.com/facebookresearch/segment-anything.git

"""## Load Pretrained Model Weights from Google Drive"""

from google.colab import drive
drive.mount("/content/drive")

"""## Prepare Automobile input images"""

!cp "/content/drive/MyDrive/SAFIRE files/safire.pth" .
!cp "/content/drive/MyDrive/SAFIRE files/sam_vit_b_01ec64.pth" .
!cp "/content/drive/MyDrive/SAFIRE files/car.jpg" ForensicsEval/inputs/

"""## Run SAFIRE Binary Forgery Localization"""

!python infer_binary.py --resume=safire.pth

"""## Verify Generated Localization Maps

These are for the test car images and the test images that came with implementing SAFIRE.
"""

import glob
from PIL import Image
from IPython.display import display

output_files = glob.glob("ForensicsEval/outputs_binary/*")
print(output_files)

for file_path in output_files:
    display(Image.open(file_path))

"""## Generate Original Map and Overlay Review Panels for 1 car image example"""

from pathlib import Path
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

input_path = Path("ForensicsEval/inputs/car.jpg")
output_dir = Path("ForensicsEval/outputs_binary")


map_path = next(output_dir.glob("car.jpg*"))

original = Image.open(input_path).convert("RGB")
score_map = Image.open(map_path).convert("L").resize(original.size)

scores = np.asarray(score_map) / 255.0

# Colouring only higher-scoring areas for visual review.
review_threshold = 0.40
alpha = np.clip((scores - review_threshold) / (1 - review_threshold), 0, 1) * 0.65

heatmap_rgb = (plt.cm.turbo(scores)[..., :3] * 255).astype(np.uint8)
original_array = np.asarray(original)

overlay = (
    original_array * (1 - alpha[..., None])
    + heatmap_rgb * alpha[..., None]
).astype(np.uint8)

fig, axes = plt.subplots(1, 3, figsize=(18, 6))

axes[0].imshow(original)
axes[0].set_title("Original automobile image")

axes[1].imshow(scores, cmap="gray", vmin=0, vmax=1)
axes[1].set_title("SAFIRE suspicion map\nDark = lower; bright = higher")

axes[2].imshow(overlay)
axes[2].set_title(f"Review overlay (scores ≥ {review_threshold:.2f})")

for axis in axes:
    axis.axis("off")

plt.tight_layout()
plt.savefig("safire_review_panel.png", dpi=200, bbox_inches="tight")
plt.show()

"""## Uploading more example test images from Google Drive"""

from google.colab import files
from pathlib import Path
import shutil

uploaded = files.upload()

input_dir = Path("ForensicsEval/inputs")

for filename in uploaded:
    file_path = Path(filename)
    if file_path.suffix.lower() in {".jpg", ".jpeg", ".png"}:
        shutil.move(str(file_path), input_dir / file_path.name)

!ls -lh ForensicsEval/inputs

!ls -lh ForensicsEval/outputs_binary

!python infer_binary.py --resume=safire.pth

"""## Generate Original Map and Overlay Review Panels for all Example Images"""

from pathlib import Path
import numpy as np
from PIL import Image
import matplotlib.pyplot as plt

input_dir = Path("ForensicsEval/inputs")
output_dir = Path("ForensicsEval/outputs_binary")
panel_dir = Path("review_panels")
panel_dir.mkdir(exist_ok=True)

for image_path in input_dir.iterdir():
    if image_path.suffix.lower() not in {".jpg", ".jpeg", ".png"}:
        continue

    map_path = output_dir / f"{image_path.name}.png"
    if not map_path.exists():
        print(f"No SAFIRE map found for {image_path.name}")
        continue

    original = Image.open(image_path).convert("RGB")
    score_map = Image.open(map_path).convert("L").resize(original.size)

    scores = np.asarray(score_map) / 255.0
    heatmap = (plt.cm.turbo(scores)[..., :3] * 255).astype(np.uint8)

    # A display setting only—not a claim that every highlighted pixel is forged.
    threshold = 0.40
    alpha = np.clip((scores - threshold) / (1 - threshold), 0, 1) * 0.65
    overlay = (
        np.asarray(original) * (1 - alpha[..., None])
        + heatmap * alpha[..., None]
    ).astype(np.uint8)

    fig, axes = plt.subplots(1, 3, figsize=(18, 6))
    axes[0].imshow(original); axes[0].set_title("Original")
    axes[1].imshow(scores, cmap="gray", vmin=0, vmax=1); axes[1].set_title("SAFIRE suspicion map")
    axes[2].imshow(overlay); axes[2].set_title("Review overlay")

    for axis in axes:
        axis.axis("off")

    plt.tight_layout()
    panel_path = panel_dir / f"{image_path.stem}_review.png"
    plt.savefig(panel_path, dpi=200, bbox_inches="tight")
    # plt.close()

    print(f"Created: {panel_path}")

# display(Image.open("review_panels/car_review.png"))

"""As can be seen from the above review panel, the first car image has been almost completely mmanipulated. The picture in the last car does not show a lot of forgery localization in the SAFIRE suspicion map, which indicates that the image could be original or entirely AI-generated. For the second last car, we can see that the car image has been edited into the original one."""

from google.colab import files

files.download("ForensicsEval/outputs_binary/car.jpg.png")

files.download("ForensicsEval/outputs_binary/car1.jpg.png")

files.download("ForensicsEval/outputs_binary/car3.png.png")